# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: hg38  # [hg19, GRCh37, mm10, rn5]
    # include a lane (run group ID) for each sample
    # lane: 1
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    algorithm:
      aligner: hisat2 # [tophat2, star]
      quality_format: Standard # [standard, illumina]
      #disambiguate: [mm10]
      trim_reads: false # read_through # false # read_through
      #adapters: [truseq, polya]
