# Cancer tumor/normal calling evaluation using synthetic dataset 3
# from the ICGC-TCGA DREAM challenge:
# https://www.synapse.org/#!Synapse:syn312572/wiki/62018
---
details:
- algorithm:
    vcfanno: /home/vsaveliev/bcbio/genomes/Hsapiens/hg19/variation/vcfanno.toml
    aligner: none
    mark_duplicates: true
    recalibrate: false
    realign: false
    variantcaller: [freebayes]
    variant_regions: ../input/NGv3.chr21.4col.bed
    sv_regions: ../input/NGv3.chr21.4col.bed
    coverage: ../input/NGv3.chr21.4col.bed
    svprioritize: ../input/sv_prio.bed
    svcaller: [seq2c, cnvkit]
    tools_on: [qualimap_full, damage_filter]
    effects_transcripts: canonical_cancer
  analysis: variant2
  description: syn3-normal
  files: ../input/syn3-normal.bam
  genome_build: hg19
- algorithm:
    vcfanno: /home/vsaveliev/bcbio/genomes/Hsapiens/hg19/variation/vcfanno.toml
    aligner: none
    mark_duplicates: true
    recalibrate: false
    realign: false
    variantcaller: [freebayes]
    variant_regions: ../input/NGv3.chr21.4col.bed
    sv_regions: ../input/NGv3.chr21.4col.bed
    coverage: ../input/NGv3.chr21.4col.bed
    svprioritize: ../input/sv_prio.bed
    svcaller: [seq2c, cnvkit]
    tools_on: [qualimap_full, damage_filter]
    effects_transcripts: canonical_cancer
  analysis: variant2
  description: syn3-tumor
  files: ../input/syn3-tumor.bam
  genome_build: hg19
fc_date: '2014-08-13'
fc_name: dream_chr21_unpaired
upload:
  dir: ../final
